// Quick-start presets. These are NOT hard-coded app templates — they simply
// pre-fill the prompt box. Every project (preset or free-form) is generated by
// the universal domain-inference + code-generation engine.

export interface Preset {
  id: string;
  name: string;
  emoji: string;
  description: string;
  tags: string[];
  gradient: string;
  prompt: string;
}

export const PRESETS: Preset[] = [
  {
    id: "capacity-forecast",
    name: "Capacity Forecast",
    emoji: "📈",
    description: "Resource capacity planning with demand forecasting, allocation, and utilization analytics",
    tags: ["Forecasting", "Scenarios", "Charts", "Utilization"],
    gradient: "from-sky-500/20 to-indigo-500/20",
    prompt:
      "Build a capacity forecasting and resource planning application. Track resources (people, teams, machines) with their capacity in hours or FTE, define planning periods by week/month/quarter, record forecasted and actual demand per period with baseline/optimistic/pessimistic scenarios, allocate resource capacity against demand, and compute utilization percentage and forecast variance. Include a dashboard with utilization trend charts, over-allocation warnings, scenario comparison, role-based access, and CSV export of capacity reports.",
  },
  {
    id: "inventory",
    name: "Inventory Control",
    emoji: "📦",
    description: "Multi-warehouse stock levels, movements, and reorder alerts",
    tags: ["Warehouse", "Stock", "Reorder"],
    gradient: "from-amber-500/20 to-orange-500/20",
    prompt:
      "Build an inventory management system to track products with SKUs across multiple warehouses, record stock levels with reserved quantities, log inbound/outbound/transfer movements, and trigger low-stock reorder alerts. Include search, filtering by category and warehouse, stock valuation reporting, and CSV export.",
  },
  {
    id: "crm",
    name: "Sales CRM",
    emoji: "🤝",
    description: "Contacts, companies, deal pipeline, and activity logging",
    tags: ["Pipeline", "Kanban", "Deals"],
    gradient: "from-emerald-500/20 to-teal-500/20",
    prompt:
      "Build a CRM to manage companies, contacts, and sales deals moving through a pipeline (lead, qualified, proposal, negotiation, won, lost). Log calls, emails, and meetings as activities against deals. Include a kanban deal board with drag and drop, pipeline value metrics, win rate reporting, owner assignment, and notifications on stage change.",
  },
  {
    id: "helpdesk",
    name: "Support Desk",
    emoji: "🎫",
    description: "Tickets, SLA policies, threaded replies, and response metrics",
    tags: ["Tickets", "SLA", "Comments"],
    gradient: "from-rose-500/20 to-pink-500/20",
    prompt:
      "Build a customer support helpdesk with tickets that have status, priority, and assignee, threaded public and internal replies, and SLA policies defining response and resolution targets per priority. Track first response time, resolution rate, and SLA breaches on a dashboard. Include search, filters, and email notifications.",
  },
  {
    id: "iot",
    name: "IoT Telemetry",
    emoji: "📡",
    description: "Device fleet, time-series readings, and threshold alerting",
    tags: ["Real-time", "Sensors", "Alerts"],
    gradient: "from-cyan-500/20 to-blue-500/20",
    prompt:
      "Build an IoT monitoring platform that registers devices and sensors with online/offline status, ingests time-series readings with metric name, value, and unit, and raises alerts on threshold breaches with info/warning/critical severity. Include real-time dashboards with charts, device uptime metrics, alert acknowledgement workflow, and filtering by location.",
  },
  {
    id: "healthcare",
    name: "Clinic Manager",
    emoji: "🏥",
    description: "Patients, providers, appointments, and clinical encounters",
    tags: ["Scheduling", "Records", "Audit"],
    gradient: "from-violet-500/20 to-purple-500/20",
    prompt:
      "Build a clinic management system with patient demographic records, provider profiles by specialty, appointment scheduling with status tracking (scheduled, checked in, completed, no-show, cancelled), and clinical encounter notes with diagnosis codes. Include a calendar view, no-show rate metrics, role-based access control, and an audit trail for compliance.",
  },
];

export const TEMPLATES = PRESETS; // legacy alias

// Icon for any inferred domain (covers packs that aren't in the preset list)
const DOMAIN_ICONS: Record<string, string> = {
  "capacity-forecast": "📈", inventory: "📦", crm: "🤝", helpdesk: "🎫",
  hr: "🧑‍💼", finance: "💰", healthcare: "🏥", education: "🎓",
  logistics: "🚚", realestate: "🏠", iot: "📡", events: "🎟️",
  "project-mgmt": "✅", cms: "📝", ecommerce: "🛍️", analytics: "📊",
  "ai-chat": "🤖", restaurant: "🍽️", fitness: "🏋️", custom: "✨",
};

export function domainIcon(id: string | null | undefined): string {
  if (!id) return "📦";
  return PRESETS.find((p) => p.id === id)?.emoji ?? DOMAIN_ICONS[id] ?? "📦";
}
