import { NextRequest, NextResponse } from "next/server";
import JSZip from "jszip";
import { db } from "@/db";
import { fileNodes, projects, environmentVariables } from "@/db/schema";
import { eq } from "drizzle-orm";

export async function GET(
  _req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;

    const [project] = await db.select().from(projects).where(eq(projects.id, id));
    if (!project) {
      return NextResponse.json({ error: "Project not found" }, { status: 404 });
    }

    const files = await db
      .select()
      .from(fileNodes)
      .where(eq(fileNodes.projectId, id));

    const envVars = await db
      .select()
      .from(environmentVariables)
      .where(eq(environmentVariables.projectId, id));

    const zip = new JSZip();

    for (const file of files) {
      if (file.type === "file") {
        zip.file(file.path, file.content ?? "");
      } else {
        // ensure empty directories are represented
        zip.folder(file.path);
      }
    }

    // Add a generated .env.example with declared variables
    if (envVars.length > 0) {
      const envContent = envVars
        .map((e) => `# ${e.description ?? ""}\n${e.key}=${e.type === "vault_ref" ? e.value : e.isSecret ? "" : e.value ?? ""}`)
        .join("\n\n");
      zip.file(".env.example", envContent);
    }

    // Add a README describing the project and generation metadata
    const readme = `# ${project.name}

${project.description ?? ""}

## Generated by EDL (End-to-End Design Lab)

- **Mode:** ${project.mode}
- **Status:** ${project.status}
- **Generated on:** ${new Date().toISOString()}

## Original Requirements

${project.prompt}

## Getting Started

\`\`\`bash
npm install
cp .env.example .env
npm run dev
\`\`\`
`;
    zip.file("README.md", readme);

    const blob = await zip.generateAsync({ type: "arraybuffer" });

    return new NextResponse(blob, {
      status: 200,
      headers: {
        "Content-Type": "application/zip",
        "Content-Disposition": `attachment; filename="${project.name.replace(/[^a-z0-9-_]/gi, "-")}.zip"`,
      },
    });
  } catch (error) {
    console.error("Failed to generate download:", error);
    return NextResponse.json({ error: "Failed to generate download" }, { status: 500 });
  }
}
